version: '3'
services:

# Nginx server configuration   
#  web:
#    image: nginx:1.17
#    container_name: webserver
#    depends_on:
#      - mysql
#      - php
#    links:
#      - mysql
#      - php
#    volumes:
#      - ./nmp_i1/volumes/data/nginx:/var/www/html
#      - ./nmp_i1/volumes/config/nginx:/etc/nginx/conf.d/
#    ports:
#      - "8080:80"

# Php-fpm configuration
#  php:
#    image: php:7.2-fpm
#    volumes:
#      - ./nmp_i1/volumes/data/nginx:/var/www/html
#      - ./nmp_i1/volumes/config/php:/usr/local/etc/php/php.ini

# MongoDB configuration
  mongodb:
    image: 'mongo'
    container_name: mongodb
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=mongo_demo
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
        - /golang-stack/volumes/data/mongodb/init.mongo.js:/docker-entrypoint-initdb.d/init.mongo.js:ro
        - /golang-stack/volumes/config/mongodb:/data/db
    ports:
        - "27017-27019:27017-27019"

# PHPMyAdmin configuration        
#  myadmin:
#    image: phpmyadmin:5.1.1
#    container_name: phpmyadmin
#    ports:
#        - "8081:80"
#    environment:
#        - PMA_ARBITRARY=1
#        - PMA_HOST=mysql
#    restart: always
#    depends_on:
#        - mysql#
